ergebnis/php-cs-fixer-config

.github/CONTRIBUTING.md

This PR
🙇 Thank you,  @linuxjuggler!

fix a typo in the CONTRIBUTING file

---

README.md

Fix: References in README.md

---

composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon
test/Unit/FactoryTest.php
test/Unit/RuleSet/AbstractRuleSetTestCase.php

Enhancement: Update phpstan/phpstan and friends

---

.php_cs
composer.json
composer.lock
src/License/File.php
src/License/Template.php
test/Unit/License/FileTest.php
test/Unit/License/TemplateTest.php

Enhancement: Write license to file

---

.github/workflows/license.yml

Enhancement: Automatically update license year at 00:01 on January 1st

---

.github/workflows/continuous-integration.yml
Makefile
composer.json
composer.lock

Enhancement: Synchronize with ergebnis/php-library-template

---

test/Unit/FactoryTest.php

Fix: Remove useless test

---

.github/actions/composer/composer/determine-cache-directory/action.yaml

Enhancement: Synchronize with ergebnis/php-cs-fixer-config-template

---

README.md

Enhancement: Modernize code examples

---

test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Assertion messages

---

phpstan-baseline.neon
test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Add type declarations where possible

---

src/RuleSet/Laravel6.php
src/RuleSet/Php71.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
test/Unit/RuleSet/AbstractRuleSetTestCase.php
test/Unit/RuleSet/Laravel6Test.php
test/Unit/RuleSet/Php71Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

Fix: Expand rule sets

---

test/Unit/FactoryTest.php
test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Rename data providers

---

psalm-baseline.xml
test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Rename methods

---

test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Assertions

---

psalm-baseline.xml
test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Rename method

---

psalm-baseline.xml
src/Factory.php
src/RuleSet.php
src/RuleSet/AbstractRuleSet.php
test/Unit/FactoryTest.php
test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: DocBlock

---

psalm-baseline.xml
test/Fixture/Config/RuleSet/DummyRuleSet.php
test/Unit/FactoryTest.php

Enhancement: Extract concrete class

---

CHANGELOG.md
src/RuleSet/Php73.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

Fix: Disable heredoc_indentation fixer

---

test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Sort fixers

---

test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Comment

---

test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Rename variables

---

test/Unit/RuleSet/AbstractRuleSetTestCase.php

Fix: Rename variable

---

composer.json
composer.lock

This PR
💁‍♂️ For reference, see https://github.com/ergebnis/test-util/compare/1.3.0...1.4.0.

Enhancement: Update ergebnis/test-util

---

CHANGELOG.md
composer.json
composer.lock

This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.17.0...v2.17.1.

Fix: Update friendsofphp/php-cs-fixer

---

composer.json
composer.lock

This PR
💁‍♂️ For reference, see https://github.com/phpstan/phpstan/compare/0.12.52...0.12.59.

Fix: Update phpstan/phpstan

---

phpstan-baseline.neon
phpstan.neon
test/Unit/RuleSet/ExplicitRuleSetTestCase.php
test/Unit/RuleSet/Php71Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

Enhancement: Extract ExplicitRuleSetTestCase

---

CHANGELOG.md
README.md
src/RuleSet/Faker.php
test/Unit/RuleSet/FakerTest.php

Enhancement: Add rule set for fakerphp/faker

---

.php_cs
LICENSE.md
src/Factory.php
src/RuleSet.php
src/RuleSet/AbstractRuleSet.php
src/RuleSet/ExplicitRuleSet.php
src/RuleSet/Faker.php
src/RuleSet/Laravel6.php
src/RuleSet/Php71.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
src/RuleSet/PhpUnit.php
test/AutoReview/SrcCodeTest.php
test/Double/Config/RuleSet/DummyRuleSet.php
test/Unit/FactoryTest.php
test/Unit/RuleSet/AbstractRuleSetTestCase.php
test/Unit/RuleSet/ExplicitRuleSetTestCase.php
test/Unit/RuleSet/FakerTest.php
test/Unit/RuleSet/Laravel6Test.php
test/Unit/RuleSet/Php71Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php
test/Unit/RuleSet/PhpUnitTest.php

Enhancement: Update license year

---

phpstan-baseline.neon
psalm-baseline.xml
test/Unit/RuleSet/AbstractRuleSetTestCase.php
test/Unit/RuleSet/ExplicitRuleSetTestCase.php

Enhancement: Simplify assertions

---

composer.json
composer.lock

Fix: Replace unnecessary polyfills

---

composer.json
composer.lock

Enhancement: Update vimeo/psalm

---

.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
CHANGELOG.md
README.md
composer.json
composer.lock

Fix: Drop support for PHP 7.2

---

.php-cs-fixer.php
src/Factory.php
test/AutoReview/SrcCodeTest.php
test/Unit/FactoryTest.php
test/Unit/RuleSet/AbstractRuleSetTestCase.php
test/Unit/RuleSet/ExplicitRuleSetTestCase.php

Enhancement: Use Php73 rule set

---

.github/workflows/integrate.yaml

Fix: Collect code coverage with Xdebug

---

.github/workflows/integrate.yaml
Makefile
infection.json

Fix: Configure infection/infection via infection.json

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml
CHANGELOG.md
Makefile
README.md
composer.json
composer.lock
test/Unit/RuleSet/AbstractRuleSetTestCase.php
test/Unit/RuleSet/ExplicitRuleSetTestCase.php

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.19.0...v3.0.0.

Enhancement: Update friendsofphp/php-cs-fixer

---

CHANGELOG.md

Fix: Add missing word

---

README.md

Use new cache filename

---

.github/workflows/merge.yaml

Fix: Adjust usage of octokit

---

.github/dependabot.yaml
composer.json
composer.lock

Fix: Allow installation of `symfony/filesystem:^5.0.0`

---

test/Unit/FactoryTest.php
test/Util/Helper.php

Enhancement: Pull in `Helper` from `ergebnis/test-util`

---

test/Unit/RuleSet/ExplicitRuleSetTestCase.php

Fix: Use `strpos`

---

.github/workflows/integrate.yaml
Makefile
composer.json
composer.lock
psalm-baseline.xml
test/EndToEnd/RuleSet/AbstractRuleSetTestCase.php
test/EndToEnd/RuleSet/Php80Test.php
test/EndToEnd/RuleSet/Php81Test.php
test/EndToEnd/phpunit.xml

Enhancement: Run end-to-end tests

---

.editorconfig
.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/merge.yaml
.github/workflows/release.yaml
.github/workflows/renew.yaml
.github/workflows/triage.yaml
.phive/phars.xml
README.md
test/Util/Helper.php

Enhancement: Synchronize with `ergebnis/php-cs-fixer-config-template`

---

CHANGELOG.md
infection.json
src/RuleSet/AbstractRuleSet.php
src/RuleSet/Php53.php
src/RuleSet/Php54.php
src/RuleSet/Php55.php
src/RuleSet/Php56.php
src/RuleSet/Php70.php
src/RuleSet/Php71.php
src/RuleSet/Php72.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
src/RuleSet/Php80.php
src/RuleSet/Php81.php
src/RuleSet/Php82.php

Enhancement: Do not hard-code name into rule set

---

.php-cs-fixer.php
CHANGELOG.md
README.md
src/RuleSet/Php53.php
src/RuleSet/Php54.php
src/RuleSet/Php55.php
src/RuleSet/Php56.php
src/RuleSet/Php70.php
src/RuleSet/Php71.php
src/RuleSet/Php72.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
src/RuleSet/Php80.php
src/RuleSet/Php81.php
src/RuleSet/Php82.php
test/EndToEnd/RuleSet/AbstractRuleSetTestCase.php
test/Unit/RuleSet/Php53Test.php
test/Unit/RuleSet/Php54Test.php
test/Unit/RuleSet/Php55Test.php
test/Unit/RuleSet/Php56Test.php
test/Unit/RuleSet/Php70Test.php
test/Unit/RuleSet/Php71Test.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php
test/Unit/RuleSet/Php80Test.php
test/Unit/RuleSet/Php81Test.php
test/Unit/RuleSet/Php82Test.php

Enhancement: Extract named constructor

---

.php-cs-fixer.php
README.md
test/EndToEnd/RuleSet/AbstractRuleSetTestCase.php

Fix: Introduce explaining variable

---

CHANGELOG.md
src/Factory.php
test/Unit/FactoryTest.php

Fix: Remove optional parameter

---

CHANGELOG.md
Makefile
README.md
psalm-baseline.xml
src/RuleSet/Php83.php
test/EndToEnd/RuleSet/Php83Test.php
test/Unit/RuleSet/Php83Test.php

Enhancement: Add `Config\RuleSet\Php83`

---

CHANGELOG.md
composer.json
composer.lock

💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/compare/v3.40.0...v3.40.2.

Fix: Update `friendsofphp/php-cs-fixer`

---

.github/workflows/integrate.yaml
README.md

Enhancement: Synchronize with `ergebnis/php-package-template`

---

test/Unit/FixersTest.php
test/Unit/NameTest.php
test/Unit/PhpVersionTest.php
test/Unit/RuleSetTest.php
test/Unit/RulesTest.php

Fix: Namespace

---

CHANGELOG.md
src/RuleSet/Php80.php
src/RuleSet/Php81.php
src/RuleSet/Php82.php
src/RuleSet/Php83.php
test/Unit/RuleSet/Php80Test.php
test/Unit/RuleSet/Php81Test.php
test/Unit/RuleSet/Php82Test.php
test/Unit/RuleSet/Php83Test.php

💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#multilinepromotedpropertiesfixer.

Enhancement: Enable and configure `PhpCsFixerCustomFixers/multiline_promoted_properties` fixer

---

src/PhpVersion/Major.php
src/PhpVersion/Minor.php
src/PhpVersion/Patch.php
test/Unit/PhpVersion/MajorTest.php
test/Unit/PhpVersion/MinorTest.php
test/Unit/PhpVersion/PatchTest.php

This pull request improves exception message strings.

Improve message strings

---

.github/settings.yml
.github/workflows/integrate.yaml
CHANGELOG.md
test/EndToEnd/RuleSet/AbstractRuleSetTestCase.php

Enhancement: Add support for PHP 8.4

---

CHANGELOG.md
README.md
src/RuleSet/Php84.php
test/EndToEnd/RuleSet/Php84Test.php
test/Unit/RuleSet/Php84Test.php

Enhancement: Add `Config\Ruleset\Php84` rule set

---

CHANGELOG.md
composer.json
composer.lock
src/RuleSet/Php74.php
src/RuleSet/Php80.php
src/RuleSet/Php81.php
src/RuleSet/Php82.php
src/RuleSet/Php83.php
src/RuleSet/Php84.php
test/Unit/RuleSet/Php74Test.php
test/Unit/RuleSet/Php80Test.php
test/Unit/RuleSet/Php81Test.php
test/Unit/RuleSet/Php82Test.php
test/Unit/RuleSet/Php83Test.php
test/Unit/RuleSet/Php84Test.php

💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/compare/v3.64.0...v3.65.0.

Enhancement: Update `friendsofphp/php-cs-fixer`

---

CHANGELOG.md
src/RuleSet/Php83.php
src/RuleSet/Php84.php
test/Unit/RuleSet/Php83Test.php
test/Unit/RuleSet/Php84Test.php

Enhancement: Enable `PhpCsFixerCustomFixers/typed_class_constant` fixer

---

.github/settings.yml
.github/workflows/integrate.yaml
CHANGELOG.md

Enhancement: Add support for PHP 8.5

---

CHANGELOG.md
README.md
src/RuleSet/Php85.php
test/EndToEnd/RuleSet/AbstractRuleSetTestCase.php
test/EndToEnd/RuleSet/Php85Test.php
test/Unit/RuleSet/Php85Test.php

Enhancement: Add `Config\Ruleset\Php85` rule set
