ergebnis/php-cs-fixer-config

README.md
=> Enhancement: Add note about template

.dependabot/config.yml, .github/CONTRIBUTING.md, src/Factory.php
=> Enhancement: Synchronize project tooling configuration with ergebnis/php-cs-fixer-config-template

.github/CONTRIBUTING.md, .github/workflows/continuous-integration.yml, Makefile, composer.json, composer.lock, phpstan.neon
=> Enhancement: Synchronize with ergebnis/php-library-template

.github/settings.yml, .github/workflows/continuous-integration.yml, CHANGELOG.md, composer.json, composer.lock, phpstan.neon
This PR
Related to https://github.com/ergebnis/composer-normalize/issues/266.
=> Fix: Bring back support for PHP 7.1

src/RuleSet.php, test/Unit/FactoryTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Add return type declarations

src/Factory.php, test/Unit/FactoryTest.php
=> Fix: add missing quote in error message

.github/workflows/continuous-integration.yml, .php_cs, CHANGELOG.md, composer.json, composer.lock, src/Header/Author.php, src/Header/CopyrightYears.php, src/Header/Header.php, src/Header/License.php, src/Header/Url.php, src/Header/Year.php, test/Unit/Header/AuthorTest.php, test/Unit/Header/CopyrightYearsTest.php, test/Unit/Header/HeaderTest.php, test/Unit/Header/LicenseTest.php, test/Unit/Header/UrlTest.php, test/Unit/Header/YearTest.php
=> Enhancement: Allow construction of header

src/Header/Year.php, test/Unit/Header/YearTest.php
=> Enhancement: Allow creation of Year from current UTC time

.php_cs, src/License/Author.php, src/License/CopyrightYears.php, src/License/Header.php, src/License/Notice.php, src/License/Url.php, src/License/Year.php, test/Unit/License/AuthorTest.php, test/Unit/License/CopyrightYearsTest.php, test/Unit/License/HeaderTest.php, test/Unit/License/NoticeTest.php, test/Unit/License/UrlTest.php, test/Unit/License/YearTest.php
=> Fix: Rename namespace and class

src/License/Header.php
=> Fix: Rename parameter and field

.php_cs, LICENSE, src/Factory.php, src/License/Copyright/Holder.php, src/License/Copyright/Year.php, src/License/Copyright/Years.php, src/License/File.php, src/License/Header.php, src/License/Notice.php, src/License/Template.php, src/License/Url.php, src/RuleSet.php, src/RuleSet/AbstractRuleSet.php, src/RuleSet/Laravel6.php, src/RuleSet/Php71.php, src/RuleSet/Php73.php, test/AutoReview/SrcCodeTest.php, test/Unit/FactoryTest.php, test/Unit/License/Copyright/HolderTest.php, test/Unit/License/Copyright/YearTest.php, test/Unit/License/Copyright/YearsTest.php, test/Unit/License/FileTest.php, test/Unit/License/HeaderTest.php, test/Unit/License/NoticeTest.php, test/Unit/License/TemplateTest.php, test/Unit/License/UrlTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Laravel6Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php
=> Enhancement: Update license year

CHANGELOG.md
=> Fix: Add missing release to changelog

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php
=> Enhancement: Configure php_unit_dedicate_assert fixer to target newest versions

.yamllint.yaml
=> Fix: Synchronize with ergebnis/php-cs-fixer-config-template

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php
This PR
💁‍♂️ Inspired by https://github.com/sebastianbergmann/phpunit/commit/899db927169682058ed8875c3d0c7f30c1fa4ed2.
=> Enhancement: Configure ordered_imports fixer

README.md
=> Fix: Remove example for Travis CI

README.md
=> Enhancement: Modernize example for GitHub Actions

CHANGELOG.md, src/Factory.php, src/RuleSet.php, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/FactoryTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.16.4#usage:
> **no_superfluous_phpdoc_tags** [`@Symfony`, `@PhpCsFixer`]
>
>Removes `@param`, `@return` and `@var` tags that don't provide any useful information.
>
>Configuration options:
>
>* `allow_mixed` (`bool`): whether type mixed without description is allowed (`true`) or considered superfluous (`false`); defaults to `false`
>* `allow_unused_params` (`bool`): whether param annotation without actual signature is allowed (`true`) or considered superfluous (`false`); defaults to `false`
>* `remove_inheritdoc` (`bool`): remove `@inheritDoc` tags; defaults to `false`
=> Enhancement: Enable and configure no_superfluous_phpdoc_tags fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_add_missing_param_annotation fixer to add annotation for untyped parameters only

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Methods can be static

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Use class names as keys

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Remove static variable

psalm-baseline.xml, test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: DocBlock

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Split test using data provider into separate tests

CHANGELOG.md, psalm-baseline.xml, src/RuleSet/Laravel6.php, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Laravel6Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Fix: Do not enable deprecated fixers

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order dataProvider annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order uses annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order author annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order coversNothing annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order depends annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order group annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order internal annotations

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order requires annotations

phpstan-baseline.neon, psalm-baseline.xml, test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Do not use deprecated RuleSet

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Rename methods and variables

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Remove unnecessary sort

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/alias/array_push.rst.
=> Enhancement: Enable array_push fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/namespace_notation/clean_namespace.rst.
=> Enhancement: Enable clean_namespace fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/function_notation/lambda_not_used_import.rst.
=> Enhancement: Enable lambda_not_used_import fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/alias/no_alias_language_construct_call.rst.
=> Enhancement: Enable no_alias_language_construct_call fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/string_notation/no_trailing_whitespace_in_string.rst.
=> Enhancement: Enable no_trailing_whitespace_in_string fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/function_notation/no_useless_sprintf.rst.
=> Enhancement: Enable no_useless_sprintf fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/operator/operator_linebreak.rst.
=> Enhancement: Enable and configure operator_linebreak fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/phpdoc/phpdoc_inline_tag_normalizer.rst.
=> Enhancement: Enable and configure phpdoc_inline_tag_normalizer fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/phpdoc/phpdoc_tag_casing.rst.
=> Enhancement: Enable and configure phpdoc_tag_casing fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/function_notation/regular_callable_call.rst.
=> Enhancement: Enable regular_callable_call fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/control_structure/switch_continue_to_break.rst.
=> Enhancement: Enable switch_continue_to_break fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
Follows #273.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.0/doc/rules/operator/ternary_to_elvis_operator.rst.
=> Enhancement: Enable ternary_to_elvis_operator fixer

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Enhancement: Synchronize with ergebnis/php-cs-fixer-config-template

test/Unit/RuleSet/AbstractRuleSetTestCase.php
- Improvements.
- Making the assert value equals strict.
=> Make assert equals strict

CHANGELOG.md, src/RuleSet/PhpUnit.php, test/Unit/RuleSet/PhpUnitTest.php
This PR
Follows https://github.com/sebastianbergmann/phpunit/pull/4553.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.2/doc/rules/php_unit/php_unit_test_case_static_method_calls.rst.
=> Enhancement: Enable and configure php_unit_test_case_static_method_calls fixer

CHANGELOG.md, src/RuleSet/PhpUnit.php, test/Unit/RuleSet/PhpUnitTest.php
This PR
Follows https://github.com/sebastianbergmann/phpunit/pull/4555.
=> Enhancement: Enable php_unit_set_up_tear_down_visibility fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.2/doc/rules/basic/braces.rst.
=> Enhancement: Configure braces fixer to allow single-line anonymous classes with empty body

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Configure phpdoc_order_by_value fixer to order throws annotations

CHANGELOG.md, phpstan-baseline.neon, src/RuleSet/ExplicitRuleSet.php, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Enhancement: Add ExplicitRuleSet marker interface

CHANGELOG.md, src/RuleSet/ExplicitRuleSet.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php
=> Enhancement: Require ExplicitRuleSets only not to configure rule sets

src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php
=> Fix: Do not use constants

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Use assertSame() instead of assertEquals()

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Enhancement: Assert that configuration items are sorted by key

phpstan-baseline.neon, test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Enhancement: Assert that rules and configuration options are sorted recursively

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/PhpUnit.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/PhpUnitTest.php
=> Fix: Do not configure rules using deprecated configuration options

CHANGELOG.md, src/RuleSet/ExplicitRuleSet.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php
=> Fix: Only require implementations of ExplicitRuleSet to configure every non-deprecated rule

test/Unit/FactoryTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Fix: Use assertEquals() instead of assertSame()

test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Enhancement: Return true when expected rule configuration is empty array

composer.json, composer.lock
=> Fix: Do not replace symfony/polyfill-*

CHANGELOG.md, src/RuleSet/Laravel6.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/PhpUnit.php, test/Unit/RuleSet/Laravel6Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/PhpUnitTest.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5485.
=> Fix: Do not use deprecated configuration for class_attributes_separation fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
=> Enhancement: Configure trailing_comma_in_multiline fixer to add trailing commas for arguments

CHANGELOG.md, src/RuleSet/Php80.php, test/Unit/RuleSet/Php80Test.php
=> Enhancement: Configure trailing_comma_in_multiline fixer to add trailing commas for parameters

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #400.
💁 For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.19.0/doc/rules/function_notation/phpdoc_to_property_type.rst.
=> Enhancement: Enable and configure phpdoc_to_property_type fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
=> Enhancement: Configure function_to_constant fixer to include get_called_class()

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #420.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/doc/rules/phpdoc/phpdoc_align.rst.
=> Enhancement: Configure phpdoc_align fixer to include method and property annotations

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #420.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/doc/rules/phpdoc/phpdoc_scalar.rst.
=> Enhancement: Configure phpdoc_scalar fixer to include callback

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
=> Fix: Wrong type

.github/workflows/prune.yaml
=> Fix: Use major.minor.patch version

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows https://github.com/ergebnis/php-cs-fixer-config/pull/475.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/rules/language_construct/declare_parentheses.rst.
=> Enhancement: Enable declare_parentheses fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows https://github.com/ergebnis/php-cs-fixer-config/pull/475.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/rules/control_structure/empty_loop_body.rst.
=> Enhancement: Enable and configure `empty_loop_body` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows https://github.com/ergebnis/php-cs-fixer-config/pull/475.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/rules/whitespace/types_spaces.rst.
=> Enhancement: Enable and configure `types_spaces` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows https://github.com/ergebnis/php-cs-fixer-config/pull/475.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/rules/whitespace/types_spaces.rst.
=> Enhancement: Configure `class_attributes_separation` fixer to use `only_if_meta` option for elements `const` and `property`

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #461.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.1/doc/rules/class_notation/class_attributes_separation.rst.
=> Enhancement: Configure `class_attributes_separation` fixer to use `none` option for element `trait_import`

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
=> Fix: Stop using deprecated `use_trait` option for `no_extra_blank_lines` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/operator/assign_null_coalescing_to_coalesce_equal.rst.
=> Enhancement: Enable `assign_null_coalescing_to_coalesce_equal` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/control_structure/control_structure_continuation_position.rst.
=> Enhancement: Enable and configure `control_structure_continuation_position` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/control_structure/empty_loop_condition.rst.
=> Enhancement: Enable and configure `empty_loop_condition` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/casing/integer_literal_case.rst.
=> Enhancement: Enable `integer_literal_case` fixer

CHANGELOG.md, src/RuleSet/Php80.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/alias/modernize_strpos.rst.
=> Enhancement: Enable `modernize_strpos` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/operator/no_space_around_double_colon.rst.
=> Enhancement: Enable `no_space_around_double_colon` fixer

CHANGELOG.md, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php
Follows #495.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/doc/rules/string_notation/string_length_to_empty.rst.
=> Enhancement: Enable `string_length_to_empty` fixer

.github/workflows/integrate.yaml
=> Fix: Do not cache cache directories for phpstan/phpstan and vimeo/psalm

psalm-baseline.xml, src/RuleSet/AbstractRuleSet.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Double/Config/RuleSet/DummyRuleSet.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
=> Fix: Add property type declarations

.php-cs-fixer.php, src/RuleSet/AbstractRuleSet.php, test/Double/Config/RuleSet/DummyRuleSet.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php
=> Enhancement: Use `Php74` rule set

test/Unit/FactoryTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php
=> Fix: Imports

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #545.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.5.0/doc/rules/language_construct/get_class_to_class_keyword.rst.
=> Enhancement: Enable `get_class_to_class_keyword` fixer

CHANGELOG.md, README.md
=> Fix: Use dashes instead of asterisks for unordered lists

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #565.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.6.0/doc/rules/casing/class_reference_name_casing.rst.
=> Enhancement: Enable `class_reference_name_casing` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #565.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.6.0/doc/rules/import/no_unneeded_import_alias.rst.
=> Enhancement: Enable `no_unneeded_import_alias` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #578.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc/rules/function_notation/no_trailing_comma_in_singleline_function_call.rst.
=> Enhancement: Enable `no_trailing_comma_in_singleline_function_call` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #578.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc%2Frules%2Fcomment%2Fsingle_line_comment_spacing.rst.
=> Enhancement: Enable `single_line_comment_spacing` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc/rules/whitespace/blank_line_before_statement.rst.
=> Enhancement: Configure `blank_line_before_statement` fixer to include additional statements

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc/rules/control_structure/no_unneeded_control_parentheses.rst.
=> Enhancement: Configure `no_unneeded_control_parentheses` fixer to include additional statements

CHANGELOG.md, src/RuleSet/Php81.php, test/Unit/RuleSet/Php81Test.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc%2Frules%2Fclass_notation%2Fordered_class_elements.rst.
=> Enhancement: Configure `ordered_class_elements` fixer to order more elements

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc/rules/phpdoc/phpdoc_align.rst.
=> Enhancement: Configure `phpdoc_align` fixer to align more tags

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.7.0/doc%2Frules%2Fclass_notation%2Fsingle_class_element_per_statement.rst.
=> Enhancement: Configure `single_class_element_per_statement` fixer to enforce single class element for `const` statements

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #591.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/function_notation/date_time_create_from_format_call.rst.
=> Enhancement: Enable `date_time_create_from_format_call` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #591.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/doc/rules/whitespace/types_spaces.rst.
=> Enhancement: Configure `types_spaces` fixer to enforce no space between types when catching multiple exceptions

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/control_structure/control_structure_braces.rst.
=> Enhancement: Enable `control_structure_braces` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/basic/curly_braces_position.rst.
=> Enhancement: Enable and configure `curly_braces_position` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/whitespace/statement_indentation.rst.
=> Enhancement: Enable `statement_indentation` fixer

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/control_structure/trailing_comma_in_multiline.rst.
=> Enhancement: Configure `trailing_comma_in_multiline` fixer to include `match` in `elements` option

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/language_construct/single_space_after_construct.rst.
=> Enhancement: Configure `single_space_after_construct` fixer to include `type_colon` in `constructs` option

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/phpdoc/phpdoc_order_by_value.rst.
=> Enhancement: Configure `phpdoc_order_by_value` fixer to include `mixin` in `annotations` option

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #620.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.1/doc/rules/whitespace/no_extra_blank_lines.rst.
=> Enhancement: Configure `no_extra_blank_lines` fixer to include `attribute` in `tokens` option

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #636.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.5/doc/rules/basic/no_multiple_statements_per_line.rst.
=> Enhancement: Enable `no_multiple_statements_per_line` fixer

CHANGELOG.md, psalm-baseline.xml, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
=> Fix: Require all configurable rules to be explicitly configured when enabled

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
=> Enhancement: Enable `ensure_single_space` option of `whitespace_after_comma_in_array` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #642.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/doc/rules/control_structure/no_alternative_syntax.rst.
=> Enhancement: Enable `fix_non_monolithic_code` option of `no_alternative_syntax` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.11.0/doc/rules/basic/no_trailing_comma_in_singleline.rst.
=> Enhancement: Configure `no_trailing_comma_in_singleline` fixer to include `group_import`

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php
Follows #661.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.12.0/doc/rules/operator/no_useless_concat_operator.rst.
=> Enhancement: Enable and configure `no_useless_concat_operator` fixer

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Enhancement: Configure `phpdoc_order` fixer to order additional annotations

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/FactoryTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #710.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.14.0/doc/rules/php_unit/php_unit_data_provider_static.rst.
=> Enhancement: Enable `php_unit_data_provider_static` fixer

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #746.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.16.0/doc/rules/language_construct/single_space_around_construct.rst.
=> Enhancement: Configure `constructs_contain_a_single_space` option of `single_space_around_construct` fixer for `yield from` constructs

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.16.0/doc/rules/phpdoc/phpdoc_separation.rst.
=> Enhancement: Configure `phpdoc_separation` fixer to group `@deprecated` annotations into a separate group

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.16.0/doc/rules/php_unit/php_unit_internal_class.rst.
=> Fix: Disable `php_unit_internal_class` fixer

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.16.0/doc/rules/php_unit/php_unit_test_class_requires_covers.rst.
=> Fix: Disable `php_unit_test_class_requires_covers` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #787.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.17.0/doc/rules/class_notation/ordered_types.rst.
=> Enhancement: Enable and configure `ordered_types` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #787.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.17.0/doc/rules/phpdoc/phpdoc_param_order.rst.
=> Enhancement: Enable `phpdoc_param_order` fixer

src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Fix: Configure `blank_lines_before_namespace` instead of deprecated `single_blank_line_before_namespace` fixer

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #815.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.21.1/doc/rules/language_construct/nullable_type_declaration.rst.
=> Enhancement: Enable and configure `nullable_type_declaration` fixer

CHANGELOG.md, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #815.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.21.1/doc/rules/whitespace/type_declaration_spaces.rst.
=> Enhancement: Configure `type_declaration_spaces` fixer to include `property` in the `elements` option

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #825.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.22.0/doc/rules/php_unit/php_unit_data_provider_return_type.rst
=> Enhancement: Enable `php_unit_data_provider_return_type` fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #840.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.23.0/doc/rules/array_notation/return_to_yield_from.rst.
=> Enhancement: Enable `return_to_yield_from` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php
=> Fix: Target PHP versions

test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Enhancement: Assert that fixers are registered, not necessarily built-in

CHANGELOG.md, infection.json, src/RuleSet/AbstractRuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php
=> Fix: Remove `$targetPhpVersion` field and `targetPhpVersion()` method

CHANGELOG.md, infection.json, src/RuleSet/AbstractRuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php
=> Fix: Remove `name()` method from `AbstractRuleSet`

CHANGELOG.md, psalm-baseline.xml, src/RuleSet/AbstractRuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php
=> Fix: Remove `rules()` method from `AbstractRuleSet`

infection.json, psalm-baseline.xml, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Fix: Fetch custom fixers from `Config\RuleSet`

CHANGELOG.md, psalm-baseline.xml, src/RuleSet/AbstractRuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php
=> Fix: Remove constructor from `RuleSet\AbstractRuleSet`

CHANGELOG.md, src/Factory.php, src/RuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Double/Config/RuleSet/DummyRuleSet.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Fix: Rename `Config\RuleSet::targetPhpVersion()` to `Config\RuleSet::phpVersion()`

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
Follows #880.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.27.0/doc/rules/operator/long_to_shorthand_operator.rst.
=> Enhancement: Enable `long_to_shorthand_operator` fixer

CHANGELOG.md, src/ExplicitRuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php
=> Fix: Rename `Config\RuleSet\ExplicitRuleSet` to `Config\ExplicitRuleSet`

.php-cs-fixer.php, CHANGELOG.md, README.md, src/RuleSet.php, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Double/Config/RuleSet/DummyRuleSet.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Enhancement: Remove optional parameter and introduce `withHeader()` mutator

CHANGELOG.md, README.md, src/RuleSet.php, test/Unit/RuleSetTest.php
=> Enhancement: Add `Config\RuleSet::withRules()` to allow overriding `Config\Rules`

CHANGELOG.md, README.md, src/Fixers.php, src/RuleSet.php, test/Unit/FixersTest.php, test/Unit/RuleSetTest.php
=> Enhancement: Add `Config\RuleSet::withCustomFixers()` to allow merging `Config\Fixers`

CHANGELOG.md, composer.json, composer.lock, psalm-baseline.xml, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Enhancement: Require and use `erickskrauch/php-cs-fixer-custom-fixers`

CHANGELOG.md, README.md, composer.json, composer.lock, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Enhancement: Require and use `kubawerlos/php-cs-fixer-custom-fixers`

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, test/EndToEnd/RuleSet/Php53Test.php, test/EndToEnd/RuleSet/Php54Test.php, test/EndToEnd/RuleSet/Php55Test.php, test/EndToEnd/RuleSet/Php56Test.php, test/EndToEnd/RuleSet/Php70Test.php, test/EndToEnd/RuleSet/Php71Test.php, test/EndToEnd/RuleSet/Php72Test.php, test/EndToEnd/RuleSet/Php73Test.php, test/EndToEnd/RuleSet/Php74Test.php, test/EndToEnd/RuleSet/Php80Test.php, test/EndToEnd/RuleSet/Php81Test.php, test/EndToEnd/RuleSet/Php82Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php
=> Enhancement: Enable and configure `attribute_empty_parentheses` fixer

.php-cs-fixer.php, psalm-baseline.xml, psalm.xml, rector.php, test/Fixture/Rector/SortAssociativeArrayByKey/class.php.inc, test/Fixture/Rector/SortAssociativeArrayByKey/file.php.inc, test/Fixture/Rector/SortAssociativeArrayByKey/test.php.inc, test/Rector/SortAssociativeArrayByKey.php, test/Unit/Rector/SortAssociativeArrayByKey/SortAssociativeArrayByKeyTest.php, test/Unit/Rector/SortAssociativeArrayByKey/config/configured_rule.php
=> Enhancement: Keep associative arrays sorted by key

CHANGELOG.md, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.35.1/doc/rules/class_notation/class_attributes_separation.rst#elements.
=> Enhancement: Configure `case` option of `elements` option of `class_attributes_separation` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php
💁‍♂️ The `::class` pseudo constant has only been available since PHP 5.5. For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.35.1/doc/rules/language_construct/function_to_constant.rst#functions.
=> Fix: Remove `get_called_class` and `get_class` options from `functions` option of `function_to_constant` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.35.1/doc/rules/alias/no_alias_functions.rst#sets.
=> Enhancement: Enable `@all` set for `sets` option of `no_alias_functions` fixer

README.md
=> Add missing brace in example

.github/CONTRIBUTING.md, .github/workflows/integrate.yaml, .phive/phars.xml, Makefile, README.md
=> Enhancement: Synchronize with `ergebnis/php-cs-fixer-config-template`

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, .phive/phars.xml, .php-cs-fixer.php, CHANGELOG.md, composer-require-checker.json, composer.json, composer.lock, psalm-baseline.xml, rector.php, src/Fixers.php, src/PhpVersion.php, src/RuleSet.php, test/EndToEnd/RuleSet/Php80Test.php, test/Unit/FixersTest.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/ExplicitRuleSetTestCase.php
Related to https://github.com/ergebnis/phpunit-slow-test-detector/issues/369.
=> Enhancement: Add support for PHP 7.4

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/AbstractRuleSetTestCase.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
Follows #970.
💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#phpdoctypelistfixer.
=> Enhancement: Enable `phpdoc_type_list`  fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#multilinecommentopeningclosingalonefixer.
=> Enhancement: Enable `PhpCsFixerCustomFixers/multiline_comment_opening_closing_alone` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#noduplicatedarraykeyfixer.
=> Enhancement: Enable and configure `PhpCsFixerCustomFixers/no_duplicated_array_key` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#noduplicatedimportsfixer.
=> Enhancement: Enable `PhpCsFixerCustomFixers/no_duplicated_imports` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#noimportfromglobalnamespacefixer.
=> Enhancement: Enable `PhpCsFixerCustomFixers/no_import_from_global_namespace` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.18.0#phpdoctypescommaspacesfixer.
=> Enhancement: Enable `PhpCsFixerCustomFixers/phpdoc_types_comma_spaces` fixer

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, Makefile, psalm-baseline.xml
=> Enhancement: Synchronize with `ergebnis/php-package-template`

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
Follows #1005.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.49.0/doc/rules/phpdoc/phpdoc_list_type.rst.
=> Enhancement: Enable `phpdoc_list_type` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
Fixes #1008.
💁‍♂️ For reference, see
- https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.20.0?tab=readme-ov-file#noimportfromglobalnamespacefixer
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.49.0/doc/rules/import/global_namespace_import.rst
=> Enhancement: Enable and configure `global_namespace_import` instead of `PhpCsFixerCustomFixers/no_import_from_global_namespace` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
Follows #1021.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.50.0/doc/rules/phpdoc/phpdoc_array_type.rst.
=> Enhancement: Enable `phpdoc_array_type` instead of `PhpCsFixerCustomFixers/phpdoc_array_style` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.51.0/doc/rules/control_structure/no_unneeded_braces.rst.
=> Enhancement: Enable `namespaces` option of `no_unneeded_braces` fixer

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
Follows #1058.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.55.0/doc/rules/attribute_notation/ordered_attributes.rst.
=> Enhancement: Enable and configure `ordered_attributes` fixer

CHANGELOG.md, src/Factory.php, test/Unit/FactoryTest.php
=> Enhancement: Enable parallel runner

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php
=> Enhancement: Configure `trailing_comma_in_multiline` fixer to include `array_destructuring` in `elements` option

CHANGELOG.md, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, src/RuleSet/Php84.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php, test/Unit/RuleSet/Php84Test.php
Follows #1153.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.68.0/doc/rules/alias/modernize_strpos.rst.
=> Enhancement: Enable `modernize_stripos` option of `modernize_strpos` fixer

CHANGELOG.md, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, src/RuleSet/Php84.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php, test/Unit/RuleSet/Php84Test.php
Follows #1177.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.70.0/doc/rules/whitespace/type_declaration_spaces.rst.
=> Enhancement: Add `constant` to `elements` option of `type_declaration_spaces` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, src/RuleSet/Php84.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php, test/Unit/RuleSet/Php84Test.php
=> Enhancement: Enable and configure `php_unit_data_provider_method_order` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, src/RuleSet/Php84.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php, test/Unit/RuleSet/Php84Test.php
Follows https://github.com/ergebnis/php-cs-fixer-config/pull/1193.
=> Enhancement: Enable `PhpCsFixerCustomFixers/php_unit_requires_constraint` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, src/RuleSet/Php84.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php, test/Unit/RuleSet/Php84Test.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.75.0/doc/rules/language_construct/single_space_around_construct.rst.
=> Enhancement: Add `as`, `else`, and `elseif` to `constructs_preceded_by_a_single_space` option of `single_space_around_construct` fixer

CHANGELOG.md, src/RuleSet/Php53.php, src/RuleSet/Php54.php, src/RuleSet/Php55.php, src/RuleSet/Php56.php, src/RuleSet/Php70.php, src/RuleSet/Php71.php, src/RuleSet/Php72.php, src/RuleSet/Php73.php, src/RuleSet/Php74.php, src/RuleSet/Php80.php, src/RuleSet/Php81.php, src/RuleSet/Php82.php, src/RuleSet/Php83.php, src/RuleSet/Php84.php, test/Unit/RuleSet/Php53Test.php, test/Unit/RuleSet/Php54Test.php, test/Unit/RuleSet/Php55Test.php, test/Unit/RuleSet/Php56Test.php, test/Unit/RuleSet/Php70Test.php, test/Unit/RuleSet/Php71Test.php, test/Unit/RuleSet/Php72Test.php, test/Unit/RuleSet/Php73Test.php, test/Unit/RuleSet/Php74Test.php, test/Unit/RuleSet/Php80Test.php, test/Unit/RuleSet/Php81Test.php, test/Unit/RuleSet/Php82Test.php, test/Unit/RuleSet/Php83Test.php, test/Unit/RuleSet/Php84Test.php
Follows #1235.
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.76.0/doc/rules/class_notation/static_private_method.rst.
=> Enhancement: Enable `static_private_method` fixer
